'reinit'
'open F:\Programming\grads\ctl\pc1.ctl'
'set t 0.5 35.5'
'set gxout bar'
'set vpage 1 11 1 5.0'
'set ylint 1'
'set xlint 1'
'set vrange -3 3'
'set xlopts 1 5 0.15'
'set ylopts 1 5 0.15'
'set xlpos 0 b'
'set ylpos 0 l'
*'set parea 1 12 1 8.5'
'set bargap 20'
'set barbase 0'
'set grid off'
'set grads off'
'd s'
'printim F:\Pic\work1\NCEP\NCEP.SAT.PC1.png white'
*'printim F:\Pic\work1\NCEP\NCEP.SAT.PC1.MovingTT_5a.ps white'
;