'reinit'
'open F:\Grads\diff.ctl'
'set parea 1 10.5 1 8.0'
'set mpdset lowres'
'set lon 0 180'
'set lat 0 90'
'set grid off'
'set grads off'
'set gxout shaded'
'd s'
'm=maskout(s,abs(s)-2.0)'
'set gxout shp'
*'set shpopts 15'
'set shp -pt shppt'
'd m'
'set line 20'
'set shpopts -1 3 0.05'
'draw shp shppt'
'draw map'
'printim point.png white'
;