'reinit'
'open F:\Programming\grads\ctl\sliding_corre.ctl'
'set t 0.5 46.5'
'set vpage 1 11 1 6.0'
'set gxout line'
'set xlopts 1 5 0.18'
'set ylopts 1 5 0.18'
'set grid off'
'set grads off'
*'set lfcols 2 3'
'set ylint 0.1'
'set vrange 0 1'
'set xlpos 0 b'
'set ylpos 0 l'
'set cmark 2'
'd s'
'set cstyle 2'
'set cmark 0'
'set ccolor 1'
'd c'
'printim F:\Pic\work1\RI2\ri2_ao.cor.ps white'
'printim F:\Pic\work1\RI2\ri2_ao.cor.png white'
;